/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormMenu;

import ADMIN.FormDangNhap;
import ADMIN.FormQuanLyCauHoi;
import ADMIN.FormQuanLyDKKH;
import ADMIN.FormQuanLyLichThi;
import ADMIN.FormQuanLyThiSinh;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Dell
 */
public class FormMenuQuanLy extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    FormQuanLyThiSinh jquanlyts = new FormQuanLyThiSinh();
    FormQuanLyCauHoi jcauhoi = new FormQuanLyCauHoi();

    public FormMenuQuanLy() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jQuanLyLT = new javax.swing.JButton();
        jQuanLyDT = new javax.swing.JButton();
        jQuanLyTL = new javax.swing.JButton();
        jQuanLyTS = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setLocation(new java.awt.Point(200, 200));

        jQuanLyLT.setBackground(new java.awt.Color(255, 51, 255));
        jQuanLyLT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconButton/calendar.png"))); // NOI18N
        jQuanLyLT.setText("Quản Lý Lịch Thi");
        jQuanLyLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuanLyLTActionPerformed(evt);
            }
        });

        jQuanLyDT.setBackground(new java.awt.Color(0, 255, 0));
        jQuanLyDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconButton/exam.png"))); // NOI18N
        jQuanLyDT.setText("Quản Lý Câu Hỏi");
        jQuanLyDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuanLyDTActionPerformed(evt);
            }
        });

        jQuanLyTL.setBackground(new java.awt.Color(255, 255, 51));
        jQuanLyTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconButton/folder.png"))); // NOI18N
        jQuanLyTL.setText("Quản Lý DKKH");
        jQuanLyTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuanLyTLActionPerformed(evt);
            }
        });

        jQuanLyTS.setBackground(new java.awt.Color(51, 51, 255));
        jQuanLyTS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconButton/student.png"))); // NOI18N
        jQuanLyTS.setText("Quản Lý Thí Sinh");
        jQuanLyTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuanLyTSActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jQuanLyTS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jQuanLyLT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jQuanLyDT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jQuanLyTL)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jQuanLyLT, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jQuanLyTS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jQuanLyDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jQuanLyTL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jQuanLyDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuanLyDTActionPerformed
        jcauhoi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jQuanLyDTActionPerformed

    private void jQuanLyTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuanLyTSActionPerformed
        jquanlyts.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jQuanLyTSActionPerformed

    private void jQuanLyLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuanLyLTActionPerformed
        FormQuanLyLichThi jlichthi = new FormQuanLyLichThi();
        jlichthi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jQuanLyLTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormDangNhap jdangnhap = new FormDangNhap();
        jdangnhap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jQuanLyTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuanLyTLActionPerformed
        FormQuanLyDKKH jdkkh = new FormQuanLyDKKH();
        jdkkh.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jQuanLyTLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jQuanLyDT;
    private javax.swing.JButton jQuanLyLT;
    private javax.swing.JButton jQuanLyTL;
    private javax.swing.JButton jQuanLyTS;
    // End of variables declaration//GEN-END:variables
}
