/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADMIN;

import Connector.Connector;
import ADMIN.FormDangNhap;
import CLASS.CustomtableQuanLyCauHoi;
import CLASS.TableThiSinh;
import CLASS.ThiSinh;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import CLASS.CauHoi;
import FormMenu.FormMenuQuanLy;
import THISINH.FormTheLeThi;

/**
 *
 * @author Dell
 */
public class FormQuanLyCauHoi extends javax.swing.JFrame {

    /**
     * Creates new form FormQuanLyDeThi
     */
    Connector con = new Connector();
    ArrayList<CauHoi> dsCH = new ArrayList<>();
    JTextField jt = new JTextField(30);
    FormTheLeThi jthele = new FormTheLeThi();
    

    public FormQuanLyCauHoi() {
        initComponents();
        setLocationRelativeTo(null);
        showTable();
    }

    public void showTable() {
        dsCH = con.getDataCauHoi();
        jTableCauHoi.setModel(new CustomtableQuanLyCauHoi(dsCH));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jThem = new javax.swing.JButton();
        jSUA = new javax.swing.JButton();
        jXoa = new javax.swing.JButton();
        jThoat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCAUHOI = new javax.swing.JTextField();
        jDAPAN3 = new javax.swing.JTextField();
        jDAPAN2 = new javax.swing.JTextField();
        jHINHANHCAUHOI = new javax.swing.JTextField();
        jDAPANDUNG = new javax.swing.JTextField();
        jMACAUHOI = new javax.swing.JTextField();
        jDAPAN4 = new javax.swing.JTextField();
        jDAPAN1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCauHoi = new javax.swing.JTable();
        jreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconButton/plus.png"))); // NOI18N
        jThem.setText("Thêm ");
        jThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jThemActionPerformed(evt);
            }
        });

        jSUA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconButton/mechanic.png"))); // NOI18N
        jSUA.setText("Sửa ");
        jSUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSUAActionPerformed(evt);
            }
        });

        jXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconButton/trash.png"))); // NOI18N
        jXoa.setText("Xóa");
        jXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXoaActionPerformed(evt);
            }
        });

        jThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconButton/exit.png"))); // NOI18N
        jThoat.setText("Thoát");
        jThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jThoatActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã Câu Hỏi  ");

        jLabel3.setText("Đáp Án 1");

        jLabel4.setText("Đáp án 2");

        jLabel5.setText("Đáp Án 3");

        jLabel6.setText("Đáp Án 4");

        jLabel7.setText("Đáp Án Đúng ");

        jLabel8.setText("Câu Hỏi");

        jLabel9.setText("Hình ảnh câu hỏi ");

        jMACAUHOI.setColumns(20);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Quản Lý Câu Hỏi Thi");

        jTableCauHoi.setBackground(new java.awt.Color(204, 204, 204));
        jTableCauHoi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableCauHoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCauHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCauHoiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCauHoi);

        jreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconButton/reset.png"))); // NOI18N
        jreset.setText("Reset");
        jreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jThem))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jMACAUHOI, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jSUA))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCAUHOI, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jHINHANHCAUHOI, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDAPANDUNG, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jXoa)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDAPAN1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDAPAN2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDAPAN3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDAPAN4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jreset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jThoat)
                        .addGap(24, 24, 24))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jMACAUHOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jCAUHOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDAPAN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addComponent(jDAPAN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jDAPANDUNG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jDAPAN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDAPAN4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHINHANHCAUHOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jThem)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jXoa)
                        .addComponent(jThoat)
                        .addComponent(jreset)
                        .addComponent(jSUA)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jThoatActionPerformed
        FormDangNhap jdangnhap = new FormDangNhap();
        int n = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn thoát chương trình không", "Exit", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
           FormMenuQuanLy jquanly = new FormMenuQuanLy();
            jquanly.setVisible(true);
            this.setVisible(false);
        }


    }//GEN-LAST:event_jThoatActionPerformed

    private void jThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jThemActionPerformed

        String query;

        if (jMACAUHOI.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập mã câu hỏi");
            return;
        }
        if (jCAUHOI.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập câu hỏi");
            return;
        }

        query = "Insert into CAU_HOI(MACAUHOI,CAUHOI,DAPAN1,DAPAN2,DAPAN3,DAPAN4,DAPANDUNG,HINHANHCAUHOI) values ('" + jMACAUHOI.getText() + "','" + jCAUHOI.getText() + "','" + jDAPAN1.getText()
                + "','" + jDAPAN2.getText() + "','" + jDAPAN3.getText() + "','" + jDAPAN4.getText() + "','" + jDAPANDUNG.getText() + "','" + jHINHANHCAUHOI.getText() + "')";

        con.UpdateData(query);
        showTable();

    }//GEN-LAST:event_jThemActionPerformed

    private void jXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXoaActionPerformed
        String query;
        query = "Delete from CAU_HOI where MACAUHOI = '" + jMACAUHOI.getText() + "'";
        con.UpdateData(query);
        showTable();
    }//GEN-LAST:event_jXoaActionPerformed

    private void jTableCauHoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCauHoiMouseClicked
        int index = jTableCauHoi.getSelectedRow();

        jMACAUHOI.setText(dsCH.get(index).getMaCauHoi());
        jCAUHOI.setText(dsCH.get(index).getCauHoi());
        jDAPAN1.setText(dsCH.get(index).getDapAn1());
        jDAPAN2.setText(dsCH.get(index).getDapAn2());
        jDAPAN3.setText(dsCH.get(index).getDapAn3());
        jDAPAN4.setText(dsCH.get(index).getDapAn4());
        jDAPANDUNG.setText(dsCH.get(index).getDapAnDung());
        jHINHANHCAUHOI.setText(dsCH.get(index).getHinhAnhCauHoi());

    }//GEN-LAST:event_jTableCauHoiMouseClicked

    private void jSUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSUAActionPerformed
        String query;
        query = "Update CAU_HOI set CAUHOI = '" + jCAUHOI.getText()
                + "', DAPAN1 = '" + jDAPAN1.getText() + "', DAPAN2 = '" + jDAPAN2.getText() + "',DAPAN3 = '" + jDAPAN3.getText()
                + "',DAPAN4 = '" + jDAPAN4.getText() + "', DAPANDUNG = '" + jDAPANDUNG.getText() + "',HINHANHCAUHOI = '" + jHINHANHCAUHOI.getText() + "' where MACAUHOI = '" + jMACAUHOI.getText() + "'";
        con.UpdateData(query);
        showTable();

    }//GEN-LAST:event_jSUAActionPerformed

    private void jresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresetActionPerformed
        jMACAUHOI.setText(null);
        jCAUHOI.setText(null);
        jDAPAN1.setText(null);
        jDAPAN2.setText(null);
        jDAPAN3.setText(null);
        jDAPAN4.setText(null);
        jDAPANDUNG.setText(null);
        jHINHANHCAUHOI.setText(null);
    }//GEN-LAST:event_jresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLyCauHoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jCAUHOI;
    private javax.swing.JTextField jDAPAN1;
    private javax.swing.JTextField jDAPAN2;
    private javax.swing.JTextField jDAPAN3;
    private javax.swing.JTextField jDAPAN4;
    private javax.swing.JTextField jDAPANDUNG;
    private javax.swing.JTextField jHINHANHCAUHOI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMACAUHOI;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSUA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCauHoi;
    private javax.swing.JButton jThem;
    private javax.swing.JButton jThoat;
    private javax.swing.JButton jXoa;
    private javax.swing.JButton jreset;
    // End of variables declaration//GEN-END:variables
}
